
language: python
install:
  - pip install -r requirements.txt
# command to run tests
script:
  # unit test
  - python -m pytest -v
  # linting test
  # - flake8
deploy:
#  - provider: heroku
#    api_key: c88ee5eb-f3f0-42a3-ab60-29fd967f7576
#    app: itp112
#  - provider: lambda
#    access_key_id:
#    secret_access_key:
#    function_name: askme-now
#    region: "us-east-1"
#    role: "arn:aws:iam::871485877504:role/service-role/askme-now-role-1o4tgp8g"
#    runtime: "python3.8"
#    handler_name: "lambda_handler"
#    access_key_id: "ASIA4V2E3FUAKPIAI7V6"
#    secret_access_key: "Rxc1v8iYEY2K+joqLslnbo21LVOgNJTfBzCDDJPx"
  -  provider: elasticbeanstalk
     access_key_id:
       secure: "PciNqItlk2qaXCNOSI0+g6QnBqVhWMMeWxTp2hVC/bOcAQVKwdx+UEJAZ9+O4tuEt5Z2eqUhdVetFg97upI6PPYwGLjwvrSSSb8ph0Q5Ujy5gPkOoW64/5S0DV3cSFZEoSYYz1kN7V9N6xzXydoESKzpI0EaXfW/XRX/KeNi+CmStFZxftlSNUyvFqs3HvlGSwzGzF9xYCqVJUHE77ijn3pJSufNfBv2yyIZvaO/qbyOz8FO2qSrxAOfiue3D2zu5LGgkInqE2qodifhtCORT/ZwjZEpbSX5wssdRNF8d6vfB3mMY5cyhjih+LQrOMdhd6YjNiD4QGDPjVuBVWYmejxsV9LJeHX/AakEeIL9f05y7lxG6UgEPqv3gM9ETOt8Fu4i6zyZkSolhwAokK+CdKqHEBh8+XiohGmAS/Vm+sCOtOv58eG+UHyR6YLBh3T8sOfOpxgibuT/X+1LgFPDljVfUOPbDbV2Vg8vnUQrCPQc6pIRge8bTPRjGpf2RP4CbBHqHPlbXCYMvqm+R3lFjtMUFhRN44AAYQ7xyN/IB4cuzRRzYgedFebERUMmFvohh/0BHgtCFuI6ZyqK15Uh2LzCuSJYff3zZ5oDqb24puxNleaLnzV+A9jdW1ZdRO6y9iDmpnj6ckmVsiAKlUHfW3gbvvNn4UJJIav1mr+oNOw="
     secret_access_key:
       secure: "O5anCwxJS6VFHcFRQ9pIksuyHEd6UhPOdQCaapqoDIFnTqYdXBt1FmJ9vUMwZc6em0/0T/+6lM7nE7nzaRXWH8tQvjguUduwmS+SDXXMmCUkBdEq+mvQcRFWyEv5w8nSMyUr0/tenAO6hmV4JSbB27Ot07QOhqFC3OfnTX5tCFbIG+JiJQrp8a2aIQB1zGXEqWnamo9SGC6rqDUdVmi9GYnyR97nw/wN3q2Q7AyiiHAueFW0En0bZJLaB7vuabNPWLWggU6Y5jTfjT7RLfwKZ88YwqXupiLfXmucMtRydc9rRXukIDRiulFBErIHkx1geGLkh/yfrUoyzkpPvS2yK5WdUztkJYyOvjuEUwtJZri5s/W2tWCMVMGT+8JgkG95i9WJAuhBAGnO6gCl+LbW/qbB/RrLSHLr94Lk/G+YJhZUn6cCmQqtgo4uTmeUWdo1uVt0xBfuBpCMUHRu7d6P6RVqh+bfT8pIQrqgBWbaS0x9pPr72N6UP7gczLT2g4rD1RLHGsUIae7NS9YOb3nS+7aOVi39H92u6v24qFXXy9uUBP9YFHqBd1ikExmYuoACv+VWTy7ts0Y6MYCfHNykAWmmSCCaqWOOx9CcK2nzeGprlquPk0WGs9wW+f6fPyYmwQ0y0d8mQmN483ZUzZHXWXVCkiHY6NXn2SF8bNV1WuU="
     region: us-east-1
     app: askme-now
     env: askme-now-env
     bucket_name: askmenowbucket


#after_success:
#  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
